# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS-TechPost1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS-TechPost1
  pod 'Alamofire', '~> 4.4'
  pod 'AlamofireImage', '~> 3.2'
  pod 'RealmSwift', '~> 2.6'
  pod 'AlamofireObjectMapper', '~> 4.1'
  pod 'ObjectMapper', '~> 2.2'

end
